name: Sync Subtree  # 工作流的名称

on:
  push:
    branches:
      - master  # 触发条件，当master分支有push操作时执行

jobs:
  subtree-sync:  # 定义一个名为subtree-sync的作业
    runs-on: ubuntu-latest  # 指定运行作业的虚拟环境，这里是最新的Ubuntu环境
    steps:
    - name: Checkout source repository  # 步骤名称：检出源代码仓库
      uses: actions/checkout@v3  # 使用actions/checkout@v3动作来检出代码
      with:  # 定义动作的参数
        repository: 'fakeppa/my-md'  # 源仓库的用户名/仓库名
        path: 'source-repo'
        token: ${{ secrets.MISK_JUST }}  # 使用名为SOURCE_REPO_ACCESS_TOKEN的秘密来授权访问源仓库

    - name: Checkout target repository  # 步骤名称：检出目标代码仓库
      uses: actions/checkout@v3  # 再次使用actions/checkout@v3动作来检出代码
      with:  # 定义动作的参数
        repository: 'fakeppa/fakeppa.github.io'  # 目标仓库的用户名/仓库名
        path: 'target-repo'
        token: ${{ secrets.MISK_JUST }}  # 使用名为TARGET_REPO_ACCESS_TOKEN的秘密来授权访问目标仓库
        fetch-depth: 0  # 禁用浅克隆
        

    - name: Sync subtree  # 步骤名称：同步子树
      run: |
        cd source-repo
        rm -rf .github .obsidian
        cd ..
        cd target-repo
        rm -rf src/article
        git config --local user.email "l17091799155@qq.com"  # 配置git用户邮箱
        git config --local user.name "fakeppa"  # 配置git用户名
        git add .
        git commit -m "Commit changes before subtree add"
        git subtree add -P src/article https://github.com/fakeppa/my-md master --squash

    - name: Commit and push changes  # 步骤名称：提交并推送更改
      run: |
        cd target-repo
        git config --local user.email "l17091799155@qq.com"  # 配置git用户邮箱
        git config --local user.name "fakeppa"  # 配置git用户名
        git commit -am "Sync subtree from source repository" || echo "No changes to commit"  # 提交更改，如果没有更改则打印消息
        git push  # 推送更改到远程仓库
